language: node_js
node_js:
  - "node"


env:
  global:
    - COUCHDB_VERSION=2.3.1
    - COUCHDB_USER=james
    - COUCHDB_PASSWORD=grobblefruit

addons:
  code_climate:
    repo_token: 1da6c51bb7169f6d958c2e4a626f093cfa526acb424071c6340fc47410104b74

services:
  - docker

before_install:
  - docker pull couchdb:$COUCHDB_VERSION
  - docker run -d  -e COUCHDB_USER=$COUCHDB_USER  -e COUCHDB_PASSWORD=$COUCHDB_PASSWORD -p 5984:5984 couchdb:$COUCHDB_VERSION

before_script:
  # Make sure CouchDB is up
  - while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done
  - echo "{\"couchdb\":{\"host\":\"127.0.0.1\",\"port\":5984,\"db\":\"newdb\",\"auth\":{\"username\":\"${COUCHDB_USER}\",\"password\":\"${COUCHDB_PASSWORD}\"}}}" > test.config.json && chmod 0600 test.config.json
  # - 'curl -H "Content-Type: application/json" -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@localhost:5984/newdb'
  # - 'curl -d @test/bulkdocs.json -H "Content-Type: application/json" -X POST http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@localhost:5984/newdb/_bulk_docs'
  # - 'curl -d @test/designdocs.json -H "Content-Type: application/json" -X POST http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@localhost:5984/newdb/_bulk_docs'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

notifications:
  email:
    on_success: change
    on_failure: change

after_script:
  - ./node_modules/.bin/tap --coverage-report=lcov &&  ./cc-test-reporter after-build  -t lcov --exit-code $TRAVIS_TEST_RESULT
